apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smboard-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: www.smboard.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: apache-service
                port:
                  number: 80
